alter table registros
  add column if not exists beca boolean not null default false,
  add column if not exists beca_autorizado_por text,
  add column if not exists beca_monto numeric;

create or replace view registros_view as
select
  id,
  member_id,
  kind,
  nombre,
  folio,
  mes,
  anio,
  forma_pago,
  case when current_user_role() = any (array['superadmin'::user_role, 'admin'::user_role]) then monto else null::numeric end as monto,
  case when current_user_role() = any (array['superadmin'::user_role, 'admin'::user_role]) then autogenerado else null::numeric end as autogenerado,
  estatus,
  horario,
  fecha_ingreso,
  telefono,
  bachillerato,
  atendido_por,
  comentarios,
  foto_url,
  foto_path,
  foto_iv,
  foto_salt,
  created_at,
  updated_at,
  case when current_user_role() = any (array['superadmin'::user_role, 'admin'::user_role]) then comision_tarjeta else null::numeric end as comision_tarjeta,
  folio_anterior,
  case when current_user_role() = any (array['superadmin'::user_role, 'admin'::user_role]) then saldo_pendiente else null::numeric end as saldo_pendiente,
  case when current_user_role() = any (array['superadmin'::user_role, 'admin'::user_role]) then pago1_forma_pago else null::payment_method end as pago1_forma_pago,
  case when current_user_role() = any (array['superadmin'::user_role, 'admin'::user_role]) then pago1_monto else null::numeric end as pago1_monto,
  case when current_user_role() = any (array['superadmin'::user_role, 'admin'::user_role]) then pago2_forma_pago else null::payment_method end as pago2_forma_pago,
  case when current_user_role() = any (array['superadmin'::user_role, 'admin'::user_role]) then pago2_monto else null::numeric end as pago2_monto,
  beca,
  case when current_user_role() = any (array['superadmin'::user_role, 'admin'::user_role]) then beca_autorizado_por else null::text end as beca_autorizado_por,
  case when current_user_role() = any (array['superadmin'::user_role, 'admin'::user_role]) then beca_monto else null::numeric end as beca_monto
from registros;
